# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  path_filters:
    - "!specs/**"
    - "!.claude/**"

  pre_merge_checks:
    docstrings:
      mode: "off"

  finishing_touches:
    docstrings:
      enabled: false
